name: Upload Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download DLL
        run: |
          curl -L -o test.dll https://github.com/SlivcUX/ember/releases/download/da/test.dll

      - name: Upload DLLs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dll-artifacts
          path: test.dll  # Path to the downloaded DLL
